demo/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "homepage#show"

  namespace :docs do
    resources :components, only: [:show]
    get "/", to: "pages#index", as: :index
    get "/*slug", to: "pages#show", as: :page
  end

  if defined?(Lookbook)
    mount Lookbook::Engine, at: "/lookbook"
  end
end

demo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

demo/app/models/page.rb
Page = Decant.define(dir: "content/pages", ext: ".md") do
  frontmatter :order
  frontmatter :title
end

demo/app/models/person.rb
class Person < ApplicationRecord
end

demo/app/models/yard.rb
module Yard
  module_function

  def code_object(class_name)
    ::YARD::Registry.load!(yardoc_path) if ::YARD::Registry.all.empty?
    yard_object = ::YARD::Registry.at(class_name)
    CodeObject.new(yard_object) if yard_object
  end

  def yardoc_path
    Rails.root.join(".yardoc")
  end
end

demo/app/models/yard/code_object.rb
module Yard
  class CodeObject < SimpleDelegator
    def docstring_introduction
      docstring.split("\n\n").first
    end

    def docstring_without_introduction
      remainders = docstring.split("\n\n")[1..]
      return nil unless remainders

      remainders.join("\n\n")
    end
  end
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

demo/app/controllers/docs/components_controller.rb
module Docs
  class ComponentsController < ApplicationController
    def show
      @code_object = Yard.code_object(params[:id])
      raise ActiveRecord::RecordNotFound if @code_object.nil?

      @child_classes = @code_object.children.select { |c| c.is_a?(YARD::CodeObjects::ClassObject) }.sort_by(&:name)
      @constructor = @code_object.meths.find { |meth| meth.name == :initialize }
      @constructor_arguments = if @constructor
        @constructor.tags(:param)
      else
        []
      end
      @examples = @code_object.tags(:example)
      @viewcomponent_slots = @code_object.tags(:viewcomponent_slot)

      lookbook_embeds = @code_object.tags(:lookbook_embed)
      @introduction_preview = find_example_preview(lookbook_embeds)
      @previews = find_non_example_previews(lookbook_embeds)

      respond_to do |format|
        format.html
        format.md
      end
    end

    private

    helper_method def all_components
      return @all_components if @all_components

      flowbite = Yard.code_object("Flowbite")
      child_classes = flowbite.children.select { |child|
        child.type == :class && child.inheritance_tree.map(&:path).include?("ViewComponent::Base")
      }

      @all_components = child_classes.sort_by(&:name)
    end

    # Returns the Lookbook preview with a scenario named "example"
    #
    # @return [Lookbook::Preview, nil]
    def find_example_preview(lookbook_embeds)
      return nil if lookbook_embeds.empty?

      preview_class = lookbook_embeds.first.text.strip
      return nil if preview_class.blank?

      preview = Lookbook::Engine.previews.find_by_preview_class(preview_class)
      return nil unless preview

      preview if preview.scenarios.any? { |s| s.name == "example" }
    end

    # @return [Array<Lookbook::Entity>]
    def find_non_example_previews(lookbook_embeds)
      return [] if lookbook_embeds.empty?

      preview_class = lookbook_embeds.first.text.strip
      return [] if preview_class.blank?

      preview_entity = Lookbook::Engine.previews.find_by_preview_class(preview_class)
      return [] unless preview_entity

      scenarios = preview_entity.scenarios
      scenarios.reject { |s| s.name == "example" }
    end

    helper_method def rubydoc_url(code_object)
      name = code_object.path
      slug = name.gsub("::", "/")
      "https://www.rubydoc.info/gems/flowbite-components/#{slug}.html"
    end
  end
end

demo/app/controllers/docs/pages_controller.rb
module Docs
  class PagesController < ApplicationController
    rescue_from(Decant::FileNotFound) { |exception| raise ActiveRecord::RecordNotFound, exception.message }

    def index
      first_page = all_pages.first
      redirect_to(docs_page_path(first_page.slug))
    end

    def show
      @page = Page.find(params[:slug])
      raise ActiveRecord::RecordNotFound if @page.nil?

      @next_page = next_page(@page)
      @previous_page = previous_page(@page)

      respond_to do |format|
        format.html
        format.md
      end
    end

    protected

    helper_method def all_pages
      Page.all.sort_by { |page| page.order || 0 }
    end

    def next_page(current_page)
      all_pages = all_pages()
      current_index = all_pages.index { |page| page.slug == current_page.slug }
      return nil if current_index.nil? || current_index + 1 >= all_pages.length

      all_pages[current_index + 1]
    end

    def previous_page(current_page)
      all_pages = all_pages()
      current_index = all_pages.index { |page| page.slug == current_page.slug }
      return nil if current_index.nil? || current_index - 1 < 0

      all_pages[current_index - 1]
    end
  end
end

demo/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show
  end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/formatting_helper.rb
require "rails_autolink"

module FormattingHelper
  class DocstringRenderer
    include YARD::Templates::Helpers::BaseHelper
    include YARD::Templates::Helpers::HtmlHelper

    Options = Data.define(:markup)

    attr_reader :view_context

    def initialize(content, view_context:, code_object: nil)
      @content = content
      @code_object = code_object
      @view_context = view_context
    end

    # Called by YARD::Templates::Helpers::HtmlHelper#htmlify to render the
    # docstring content. The default implementation simply returns the content
    # as is, but you can override this method to provide custom rendering logic
    # based on the specified markup format.
    def html_markup_markdown(content)
      return "" unless content
      return "" unless content.strip.present?

      output = Kramdown::Document.new(content, input: "GFM").to_html
      remove_line_breaks(output)
    end

    def render
      htmlify(@content)
    end

    private

    def object
      # Required by YARD::Templates::Helpers::HtmlHelper#resolve_links
      @code_object
    end

    def options
      @options ||= Options.new(
        markup: :markdown
      )
    end

    def remove_line_breaks(text)
      text.gsub("<br />", " ")
    end

    def linkify(name, title)
      code_object = Yard.code_object(name)
      if code_object
        view_context.link_to(title || name, view_context.docs_component_path(code_object.path))
      else
        title || name
      end
    end
  end

  def render_docstring(content, code_object: nil)
    html = DocstringRenderer.new(
      content,
      code_object: code_object,
      view_context: self
    ).render.html_safe
    auto_link(html)
  end

  def render_markdown(content)
    Kramdown::Document.new(content, input: "GFM").to_html.html_safe
  end
end

demo/app/views/docs/components/show.md.erb
# <%= @code_object.name %>

<%= simple_format(@code_object.docstring) %>

<% @code_object.tags(:example).each do |example| %>
## <%= example.name %>
```ruby
<%= example.text %>
```
<% end %>

<!-- Embedded preview iframe omitted in markdown. Add a note or link if needed. -->

## Constructor

<% @code_object.meths.select(&:constructor?).each do |meth| %>
`<%= meth.signature %>`

<%= meth.docstring %>

<% meth.parameters.each do |name, default| %>
- <%= name %>
<% end %>

<%= meth.inspect %>
<% end %>

## Instance attributes

<% @code_object.attributes[:instance].each do |name, attr| %>
- `<%= name %>`: <%= attr[:read].docstring %>
<% end %>

## Methods

<% @code_object.meths.each do |meth| %>
- `<%= meth.signature %>`

  <%= meth.docstring %>
<% end %>

## Tags

<% @code_object.tags(:param).each do |tag| %>
- **<%= tag.name %>**: <%= tag.text %>

  <%= tag.inspect %>
<% end %>

demo/app/views/docs/pages/show.html.erb
<article
  class="
    flex flex-wrap gap-8 w-full max-w-screen-xl items-center
    justify-between mx-auto
  "
>
  <nav
    id="default-sidebar"
    class="flex-none h-full transition-transform -translate-x-full sm:translate-x-0"
    aria-label="Sidebar"
  >
    <div
      class="
        h-full -ml-2 pr-6 py-4 overflow-y-auto border-e
        border-default
      "
    >
      <ul class="space-y-2 font-medium">
        <% all_pages.each do |page| %>
          <li>
            <%= link_to page.title, docs_page_path(page.slug), class: "flex items-center px-2 py-1.5 text-body rounded-base hover:bg-neutral-tertiary hover:text-fg-brand group" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <main class="py-4 flex-1">
    <div class="format dark:format-invert">
      <h1 class="mb-4 text-4xl tracking-tight font-bold text-gray-900 dark:text-white"><%= @page.title %></h1>

      <%= render_markdown(@page.content) %>
    </div>

    <div class="flex justify-between">
      <% if @previous_page %>
        <div class="mt-8">
          <%= link_to "← #{@previous_page.title}", docs_page_path(@previous_page.slug), class: "text-blue-600 hover:underline" %>
        </div>
      <% end %>

      <% if @next_page %>
        <div class="mt-8">
          <%= link_to "#{@next_page.title} →", docs_page_path(@next_page.slug), class: "text-blue-600 hover:underline" %>
        </div>
      <% end %>
    </div>
  </main>
</article>

demo/app/views/docs/pages/show.md.erb
# <%= @page.title %>

<%= @page.content %>

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title><%= content_for(:title) || "Flowbite Components for Rails" %></title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%# = tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>
  </head>

  <body class="bg-neutral-primary text-body">
    <header>
      <nav class="bg-neutral-primary border-gray-200">
        <div
          class="
            max-w-screen-xl flex flex-wrap items-center justify-between
            mx-auto p-4
          "
        >
          <%= link_to(root_path, class: "flex items-center space-x-3 rtl:space-x-reverse") do %>
            <span
              class="
                self-center text-2xl font-semibold whitespace-nowrap
                text-heading
              "
            >
              flowbite-components
            </span>
          <% end %>

          <% if @menu_toggle_implemented %>
            <button
              data-collapse-toggle="navbar-default"
              type="button"
              class="
                inline-flex items-center p-2 w-10 h-10 justify-center
                text-sm text-body rounded-lg md:hidden hover:bg-neutral-primary/10
                focus:outline-none focus:ring-2 focus:ring-primary/50
              "
              aria-controls="navbar-default"
              aria-expanded="false"
            >
              <span class="sr-only">Open main menu</span>

              <svg
                class="w-5 h-5"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 17 14"
              >
                <path
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M1 1h15M1 7h15M1 13h15"
                />
              </svg>
            </button>
          <% end %>

          <div class="hidden w-full md:block md:w-auto" id="navbar-default">
            <ul
              class="
                font-medium flex flex-col p-4 md:p-0 mt-4 border
                border-light rounded-lg bg-neutral-secondary md:flex-row
                md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0
                md:bg-neutral-primary
              "
            >
              <li>
                <%= link_to("Home", root_url, class: "block py-2 px-3 text-heading rounded-sm hover:bg-neutral-tertiary md:hover:bg-transparent md:border-0 md:hover:text-brand md:p-0 md:dark:hover:text-fg-brand dark:hover:text-white md:dark:hover:bg-transparent") %>
              </li>
              <li>
                <%= link_to("Docs", docs_index_path, class: "block py-2 px-3 text-heading rounded-sm hover:bg-neutral-tertiary md:hover:bg-transparent md:border-0 md:hover:text-brand md:p-0 md:dark:hover:text-fg-brand dark:hover:text-white md:dark:hover:bg-transparent") %>
              </li>
              <li>
                <%= link_to("Components", docs_component_path("Flowbite"), class: "block py-2 px-3 text-heading rounded-sm hover:bg-neutral-tertiary md:hover:bg-transparent md:border-0 md:hover:text-brand md:p-0 md:dark:hover:text-fg-brand dark:hover:text-white md:dark:hover:bg-transparent") %>
              </li>
              <li>
                <%= link_to("GitHub", "https://github.com/substancelab/flowbite-components", class: "block py-2 px-3 text-heading rounded-sm hover:bg-neutral-tertiary md:hover:bg-transparent md:border-0 md:hover:text-brand md:p-0 md:dark:hover:text-fg-brand dark:hover:text-white md:dark:hover:bg-transparent") %>
              </li>

              <li>
                <button data-theme-toggle="dark" class="dark:hidden">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    fill="currentColor"
                    class="size-6"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M9.528 1.718a.75.75 0 0 1 .162.819A8.97 8.97 0 0 0 9 6a9 9 0 0 0 9 9 8.97 8.97 0 0 0 3.463-.69.75.75 0 0 1 .981.98 10.503 10.503 0 0 1-9.694 6.46c-5.799 0-10.5-4.7-10.5-10.5 0-4.368 2.667-8.112 6.46-9.694a.75.75 0 0 1 .818.162Z"
                      clip-rule="evenodd"
                    />
                  </svg>
                </button>

                <button data-theme-toggle="light" class="hidden dark:block">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    stroke="currentColor"
                    class="size-6"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M12 18v-5.25m0 0a6.01 6.01 0 0 0 1.5-.189m-1.5.189a6.01 6.01 0 0 1-1.5-.189m3.75 7.478a12.06 12.06 0 0 1-4.5 0m3.75 2.383a14.406 14.406 0 0 1-3 0M14.25 18v-.192c0-.983.658-1.823 1.508-2.316a7.5 7.5 0 1 0-7.517 0c.85.493 1.509 1.333 1.509 2.316V18"
                    />
                  </svg>
                </button>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="max-w-screen-xl mx-auto p-4 flex">
      <%= yield %>
    </main>

    <footer class="max-w-screen-xl mx-auto mt-28 px-5 py-5 flex border-t-2 border-default">
      <div class="space-y-5">
        <div class="flex space-x-5">
          <%= link_to("GitHub", "https://github.com/substancelab/flowbite-components") %>
          <%= link_to("RubyGems", "https://rubygems.org/gems/flowbite-components") %>
          <%= link_to("RubyDoc documentation", "https://www.rubydoc.info/gems/flowbite-components/") %>
        </div>

        <div>
          Licensed under the
          <%= link_to("MIT License", "https://github.com/substancelab/flowbite-components/blob/main/LICENSE") %>,
          except where otherwise stated
        </div>

        <div>
          The Flowbite name and logos are trademarks of
          <%= link_to("Bergside Inc", "https://flowbite.com/brand/") %>. The
          Tailwind name and logos are trademarks of
          <%= link_to("Tailwind Labs Inc", "https://tailwindcss.com/brand") %>.
        </div>
      </div>
    </footer>

    <script>
      function setTheme(theme) {
        if (theme === "dark") {
          document.documentElement.classList.add("dark");
          document.documentElement.classList.remove("light");
        } else {
          document.documentElement.classList.add("light");
          document.documentElement.classList.remove("dark");
        }
        localStorage.setItem("theme", theme);
      }
      setTheme(localStorage.getItem("theme") || "light");

      document.querySelectorAll("[data-theme-toggle]").forEach((element) => {
        element.addEventListener("click", () => {
          const theme = element.getAttribute("data-theme-toggle");
          if (theme) {
            setTheme(theme);
          }
        });
      });
    </script>

    <%= javascript_include_tag "/lookbook-assets/js/lookbook.js" %>
  </body>
</html>

demo/app/views/layouts/preview.html.erb
<!DOCTYPE html>
<html class="<%= params.dig(:lookbook, :display, :theme) %>">
  <head>
    <title><%= content_for(:title) || "Demo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= stylesheet_link_tag :app %>
  </head>

  <body class="bg-neutral-primary text-body">
    <% if params[:lookbook_embed] %>
      <main class="flex p-5">
        <%= yield %>
      </main>
    <% else %>
      <main class="container mx-auto mt-12 flex">
        <%= yield %>
      </main>
    <% end %>
  </body>
</html>

demo/app/views/lookbook/previews/group.html.erb
<div class="<%= params.dig(:lookbook, :display, :classes) %>">
  <% if scenarios.many? %>
    <!-- Render a group of scenarios -->
    <% scenarios.each do |scenario| %>
      <div style="margin-bottom: 30px !important; display: block !important;">
        <%= scenario.output %>
      </div>
    <% end %>
  <% else %>
    <!-- Render a single scenario -->
    <%= scenarios.first.output %>
  <% end %>
</div>

demo/app/views/pages/index.html.erb
<section class="text-heading">
  <div class="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16">
    <h1
      class="
        mb-6 text-4xl font-bold tracking-tighter text-heading md:text-5xl
        lg:text-6xl
      "
    >
      Rails meets Flowbite
    </h1>

    <p class="mb-8 text-base font-normal text-body md:text-xl sm:px-16 lg:px-48">
      UI component library for Rails, built using ViewComponents, Flowbite, and
      Tailwind CSS.
    </p>

    <div
      class="
        flex flex-col space-y-4 sm:flex-row sm:justify-center sm:space-x-4
        sm:space-y-0
      "
    >
      <%= link_to("https://github.com/substancelab/flowbite-components?tab=readme-ov-file#installation", class: Flowbite::Button.classes(size: :lg) + ["inline-flex", "justify-center", "items-center"]) do %>
        Get started
        <svg
          class="w-3.5 h-3.5 ms-2 rtl:rotate-180"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 14 10"
        >
          <path
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M1 5h12m0 0L9 1m4 4L9 9"
          />
        </svg>
      <% end %>

      <%= link_to(lookbook_path, class: Flowbite::Button.classes(size: :lg, style: :secondary)) do %>
        View components
      <% end %>
    </div>
  </div>
</section>

<div class="flex flex-col gap-6 sm:flex-row">
  <%= render(Flowbite::Card.new(:class => "sm:flex-1")) do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
      class="size-7 text-body mb-3"
    >
      <path
        fill-rule="evenodd"
        d="M20.599 1.5c-.376 0-.743.111-1.055.32l-5.08 3.385a18.747 18.747 0 0 0-3.471 2.987 10.04 10.04 0 0 1 4.815 4.815 18.748 18.748 0 0 0 2.987-3.472l3.386-5.079A1.902 1.902 0 0 0 20.599 1.5Zm-8.3 14.025a18.76 18.76 0 0 0 1.896-1.207 8.026 8.026 0 0 0-4.513-4.513A18.75 18.75 0 0 0 8.475 11.7l-.278.5a5.26 5.26 0 0 1 3.601 3.602l.502-.278ZM6.75 13.5A3.75 3.75 0 0 0 3 17.25a1.5 1.5 0 0 1-1.601 1.497.75.75 0 0 0-.7 1.123 5.25 5.25 0 0 0 9.8-2.62 3.75 3.75 0 0 0-3.75-3.75Z"
        clip-rule="evenodd"
      />
    </svg>

    <%= link_to("https://flowbite.com/") do %>
      <h2 class="mb-2 text-2xl font-semibold tracking-tight text-heading">
        Designed by Flowbite
      </h2>
    <% end %>

    <p class="mb-3 font-normal text-body">
      Open-source library of over 600+ UI components, sections, and pages.
    </p>

    <%= link_to("https://flowbite.com/", class: "inline-flex font-medium items-center text-fg-brand hover:underline") do %>
      Flowbite documentation
      <svg
        class="w-3 h-3 ms-2.5 rtl:rotate-[270deg]"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 18 18"
      >
        <path
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M15 11v4.833A1.166 1.166 0 0 1 13.833 17H2.167A1.167 1.167 0 0 1 1 15.833V4.167A1.166 1.166 0 0 1 2.167 3h4.618m4.447-2H17v5.768M9.111 8.889l7.778-7.778"
        />
      </svg>
    <% end %>
  <% end %>

  <%= render(Flowbite::Card.new(:class => "sm:flex-1")) do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
      class="size-7 text-body mb-3"
    >
      <path
        d="m11.645 20.91-.007-.003-.022-.012a15.247 15.247 0 0 1-.383-.218 25.18 25.18 0 0 1-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0 1 12 5.052 5.5 5.5 0 0 1 16.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 0 1-4.244 3.17 15.247 15.247 0 0 1-.383.219l-.022.012-.007.004-.003.001a.752.752 0 0 1-.704 0l-.003-.001Z"
      />
    </svg>

    <%= link_to("https://tailwindcss.com") do %>
      <h2 class="mb-2 text-2xl font-semibold tracking-tight text-heading">
        Powered by Tailwind CSS
      </h2>
    <% end %>

    <p class="mb-3 font-normal text-body">
      Utility-first CSS framework that can be composed to build any design,
      directly in your markup.
    </p>

    <%= link_to("https://tailwindcss.com", class: "inline-flex font-medium items-center text-fg-brand hover:underline") do %>
      Tailwind CSS documentation
      <svg
        class="w-3 h-3 ms-2.5 rtl:rotate-[270deg]"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 18 18"
      >
        <path
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M15 11v4.833A1.166 1.166 0 0 1 13.833 17H2.167A1.167 1.167 0 0 1 1 15.833V4.167A1.166 1.166 0 0 1 2.167 3h4.618m4.447-2H17v5.768M9.111 8.889l7.778-7.778"
        />
      </svg>
    <% end %>
  <% end %>

  <%= render(Flowbite::Card.new(:class => "sm:flex-1")) do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
      class="size-7 text-body mb-3"
    >
      <path
        fill-rule="evenodd"
        d="M12 6.75a5.25 5.25 0 0 1 6.775-5.025.75.75 0 0 1 .313 1.248l-3.32 3.319c.063.475.276.934.641 1.299.365.365.824.578 1.3.64l3.318-3.319a.75.75 0 0 1 1.248.313 5.25 5.25 0 0 1-5.472 6.756c-1.018-.086-1.87.1-2.309.634L7.344 21.3A3.298 3.298 0 1 1 2.7 16.657l8.684-7.151c.533-.44.72-1.291.634-2.309A5.342 5.342 0 0 1 12 6.75ZM4.117 19.125a.75.75 0 0 1 .75-.75h.008a.75.75 0 0 1 .75.75v.008a.75.75 0 0 1-.75.75h-.008a.75.75 0 0 1-.75-.75v-.008Z"
        clip-rule="evenodd"
      />

      <path
        d="m10.076 8.64-2.201-2.2V4.874a.75.75 0 0 0-.364-.643l-3.75-2.25a.75.75 0 0 0-.916.113l-.75.75a.75.75 0 0 0-.113.916l2.25 3.75a.75.75 0 0 0 .643.364h1.564l2.062 2.062 1.575-1.297Z"
      />

      <path
        fill-rule="evenodd"
        d="m12.556 17.329 4.183 4.182a3.375 3.375 0 0 0 4.773-4.773l-3.306-3.305a6.803 6.803 0 0 1-1.53.043c-.394-.034-.682-.006-.867.042a.589.589 0 0 0-.167.063l-3.086 3.748Zm3.414-1.36a.75.75 0 0 1 1.06 0l1.875 1.876a.75.75 0 1 1-1.06 1.06L15.97 17.03a.75.75 0 0 1 0-1.06Z"
        clip-rule="evenodd"
      />
    </svg>

    <%= link_to("https://viewcomponent.org") do %>
      <h2 class="mb-2 text-2xl font-semibold tracking-tight text-heading">
        Built on ViewComponent
      </h2>
    <% end %>

    <p class="mb-3 font-normal text-body">
      Reusable, testable & encapsulated view components for Ruby on Rails.
    </p>

    <%= link_to("https://viewcomponent.org", class: "inline-flex font-medium items-center text-fg-brand hover:underline") do %>
      ViewComponent documentation
      <svg
        class="w-3 h-3 ms-2.5 rtl:rotate-[270deg]"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 18 18"
      >
        <path
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M15 11v4.833A1.166 1.166 0 0 1 13.833 17H2.167A1.167 1.167 0 0 1 1 15.833V4.167A1.166 1.166 0 0 1 2.167 3h4.618m4.447-2H17v5.768M9.111 8.889l7.778-7.778"
        />
      </svg>
    <% end %>
  <% end %>
</div>